import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ReactQueryProvider } from "./_providers/react-query/react-query-provider";

import Header from "@/components/navigation/header";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Ticket Bounty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full overflow-hidden antialiased font-sans",
        inter.variable,
      )}
    >
      <body className="flex flex-col">
        <NuqsAdapter>
          <ThemeProvider>
            <ReactQueryProvider>
              <SidebarProvider defaultOpen={false}>
                <AppSidebar />

                <div className="grid grid-rows-[auto_1fr] h-screen flex-1 w-full">
                  <Header />
                  <main className="flex-1 flex flex-col overflow-y-auto overflow-x-hidden p-6 pt-8 bg-background/50">
                    {children}
                  </main>
                </div>
              </SidebarProvider>

              <Toaster />
            </ReactQueryProvider>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
